language: node_js
sudo: false
node_js:
  - "7"
  - "8"
# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - tesseract-ocr
#       - g++-4.9
os:
  - osx
env:
  - CXX=g++-4.9
before_install:
  - npm install -g node-gyp@latest
  - brew update
  - brew outdated pkg-config || brew install pkg-config || brew upgrade pkg-config
  - brew outdated tesseract || brew install tesseract || brew upgrade tesseract
  - pkg-config --version
  - tesseract --version
after_success:
  - npm run report-cov
