language: node_js
sudo: false
node_js:
  - "8"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - tesseract-ocr
      - g++-4.9
env:
  - CXX=g++-4.9
before_install:
  - npm explore npm -g -- npm install node-gyp@latest
after_success:
  - npm run report-cov
